### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by virpatel524** [HackNashville6Gatton/eyePhone#1]
Hi,

Does this code do anything? 

Thanks,
Vir Patel

**Comment by PeterKaminski09** [comment]
Hi Vir,
Thanks for reaching out! We appreciate that. Basically, it doesn't do jack shit.

On Thu, Jul 9, 2015 at 10:57 PM, HackNashville6Gatton/eyePhone
reply@reply.github.com
wrote:
Hi,

Does this code do anything?

Thanks,
Vir Patel
